openapi: 3.0.0
info:
  title: Web Service Hichem - Dimitri
  version: 1.0.0
servers:
  - url: http://127.0.0.1:5000/
paths:
  /infosInsert/date/{date}/depart/{depart}/arrivee/{arrivee}/trainid/{train_id}/quantite/{quantite}/classe/{classe}:
    get:
      summary: Retrieve price for a specific date, departure, arrival, train id, quantity and class
      parameters:
        - name: date
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
        - name: depart
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
        - name: arrivee
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
        - name: train_id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
        - name: quantite
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
        - name: classe
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        '200':
          description: Price retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        '400':
          description: Invalid input provided
  /infosInsert/date/{date}/depart/{depart}/arrivee/{arrivee}/trainid/{train_id}/quantite/{quantite}:
    get:
      summary: Retrieve price for a specific date, departure, arrival, train id and quantity
      parameters:
        - name: date
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
        - name: depart
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
        - name: arrivee
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
        - name: train_id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
        - name: quantite
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        '200':
          description: Price retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        '400':
          description: Invalid input provided
  /infosInsert/date/{date}/depart/{depart}/arrivee/{arrivee}/trainid/{train_id}:
    get:
      summary: Retrieve quantity limit and price for a specific date, departure, arrival and train id
      parameters:
        - name: date
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
        - name: depart
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
        - name: arrivee
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
        - name: train_id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        '200':
          description: Quantity limit and price retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
        '400':
          description: Invalid input provided
  /infosInsert/date/{date}/depart/{depart}/arrivee/{arrivee}:
    get:
      summary: Retrieve train and class options for a specific date, departure and arrival
      parameters:
        - name: date
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
        - name: depart
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
        - name: arrivee
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        '200':
          description: Train and class options retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_2'
        '400':
          description: Invalid input provided
  /infosInsert/date/{date}/depart/{depart}:
    get:
      summary: Retrieve arrival options for a specific date and departure
      parameters:
        - name: date
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
        - name: depart
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        '200':
          description: Arrival options retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_3'
        '400':
          description: Invalid input provided
  /infosInsert/date/{date}:
    get:
      summary: Retrieve departure options for a specific date
      parameters:
        - name: date
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        '200':
          description: Departure options retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_4'
        '400':
          description: Invalid input provided
  /delete/{id}:
    delete:
      summary: Delete reservation
      parameters:
        - name: id
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: integer
      responses:
        '200':
          description: Reservation deleted successfully
        '400':
          description: Invalid input provided
  /update:
    put:
      summary: Update reservation
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/update_body'
        required: true
      responses:
        '200':
          description: Reservation updated successfully
        '400':
          description: Invalid input provided
  /insert:
    post:
      summary: Insert reservation data
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/insert_body'
        required: true
      responses:
        '200':
          description: Successfully inserted reservation data
        '400':
          description: Bad request
  /protected:
    get:
      summary: Sert a verifier l'authtification de l'utilisateur
      responses:
        '200':
          description: Successfully redirected to home page
        '401':
          description: Unauthorized
  /logout:
    get:
      summary: Logout the current user
      responses:
        '200':
          description: Successfully logged out
        '401':
          description: Unauthorized
  /login:
    post:
      summary: Login the user
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/login_body'
        required: true
      responses:
        '200':
          description: Successfully logged in
        '401':
          description: Unauthorized
  /:
    get:
      summary: Affiche la page principale
      responses:
        '200':
          description: Successfully retrieved data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_5'
components:
  schemas:
    inline_response_200:
      type: object
      properties:
        affiche_prix:
          type: string
    inline_response_200_1:
      type: object
      properties:
        quantite_limit:
          type: string
        affiche_prix:
          type: string
    inline_response_200_2:
      type: object
      properties:
        train_opt:
          type: string
        classe_opt:
          type: string
    inline_response_200_3:
      type: object
      properties:
        arrivé_option:
          type: string
    inline_response_200_4:
      type: object
      properties:
        depart_option:
          type: string
    update_body:
      type: object
      properties:
        id:
          type: integer
          example: 1
        Nom:
          type: string
          example: John Doe
        date:
          type: string
          example: '2022-01-01'
        trainid:
          type: integer
          example: 123
        Depart_reserv:
          type: string
          example: Paris
        Arrivee_reserv:
          type: string
          example: Marseille
        quantité:
          type: integer
          example: 2
    insert_body:
      type: object
      properties:
        Nom:
          type: string
          description: Name of the reservation
        date:
          type: string
          description: Date of the reservation
        trainid:
          type: string
          description: ID of the train
        Depart_reserv:
          type: string
          description: Departure station of the reservation
        Arrivee_reserv:
          type: string
          description: Arrival station of the reservation
        quantité:
          type: integer
          description: Quantity of tickets
        prix_tot:
          type: integer
          description: Total price of the reservation
    login_body:
      type: object
      properties:
        username:
          type: string
          description: The username
        password:
          type: string
          description: The password
    inline_response_200_5:
      type: object
      properties:
        reservation:
          type: array
          items:
            type: object
            properties:
              index:
                type: integer
                description: The index of the reservation
              User:
                type: integer
                description: The ID of the user who made the reservation
              Nom:
                type: string
                description: The name of the reservation
              Date:
                type: string
                description: The date of the reservation
              ID:
                type: string
                description: The ID of the train
              depart_reserv:
                type: string
                description: The departure station of the reservation
              arrivee_reserv:
                type: string
                description: The arrival station of the reservation
              Quantite:
                type: integer
                description: The quantity of tickets
              Prix:
                type: integer
                description: The total price of the reservation
        train:
          type: array
          items:
            type: object
            properties:
              ID:
                type: string
                description: The ID of the train
              depart:
                type: string
                description: The departure station of the train
              arrivee:
                type: string
                description: The arrival station of the train
              date_depart:
                type: string
                description: The departure date of the train
              heure_depart:
                type: string
                description: The departure time of the train
              date_arrivee:
                type: string
                description: The arrival date of the train
              heure_arrivee:
                type: string
                description: The arrival time of the train
              nb_places:
                type: integer
                description: The number of available seats on the train
              prix:
                type: integer
                description: The price of a ticket on the train
